// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// selfmat_cone_cpp
List selfmat_cone_cpp(IntegerMatrix ag_cone, IntegerMatrix gam_pos, IntegerVector idx1, IntegerVector idx2, IntegerVector pair_wt, NumericVector hash_weights, NumericVector cone_hashes, int m, int chunk_size, int nthreads);
RcppExport SEXP _polyfreq_selfmat_cone_cpp(SEXP ag_coneSEXP, SEXP gam_posSEXP, SEXP idx1SEXP, SEXP idx2SEXP, SEXP pair_wtSEXP, SEXP hash_weightsSEXP, SEXP cone_hashesSEXP, SEXP mSEXP, SEXP chunk_sizeSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type ag_cone(ag_coneSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type gam_pos(gam_posSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type idx1(idx1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type idx2(idx2SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type pair_wt(pair_wtSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type hash_weights(hash_weightsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cone_hashes(cone_hashesSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< int >::type chunk_size(chunk_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(selfmat_cone_cpp(ag_cone, gam_pos, idx1, idx2, pair_wt, hash_weights, cone_hashes, m, chunk_size, nthreads));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_polyfreq_selfmat_cone_cpp", (DL_FUNC) &_polyfreq_selfmat_cone_cpp, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_polyfreq(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
