# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.build_cone_cpp <- function(unique_phenos, na, na1, m2) {
    .Call(`_polyfreq_build_cone_cpp`, unique_phenos, na, na1, m2)
}

.selfmat_cone_cpp <- function(ag_cone, gam_pos, idx1, idx2, pair_wt, hash_weights, cone_hashes, m, chunk_size, nthreads) {
    .Call(`_polyfreq_selfmat_cone_cpp`, ag_cone, gam_pos, idx1, idx2, pair_wt, hash_weights, cone_hashes, m, chunk_size, nthreads)
}

